export const VERTICALS = {
  restaurant:{
    id:"restaurant",name:"Restaurante / Cafetería",icon:"🍽️",color:"#f97316",
    desc:"Restaurantes, cafeterías, bares, food trucks, dark kitchens",
    labels:{catalog:"Catálogo",item:"Plato",itemPlural:"Platos",category:"Categoría",categoryPlural:"Categorías",
      order:"Pedido",delivery:"Domicilio",branch:"Sucursal",stock:"Disponibilidad",
      design:"Diseño del catálogo",nav_products:"🍽️ Productos",nav_delivery:"🛵 Delivery / Pedidos",
      nav_design:"🎨 Diseño del catálogo",nav_stock:"📦 Fuera de stock",
      nav_branches:"🏪 Sucursales",home_products:"Platos activos",home_orders:"Pedidos hoy",
      public_title:"Catálogo Digital",btn_view:"Ver catálogo",cta:"¡Haz tu pedido!",
      cat_example:"Platos fuertes",item_example:"Bandeja paisa",item_photo:"Foto del plato",
      banner_tip:"con el plato protagonista centrado y texto corto en la imagen",
      // Customer UX labels
      featured_label:"Recomendados",popular_label:"Más pedidos",catalog_btn:"🍽️ Ver carta completa",
      how_order:"¿Cómo quieres tu pedido?",table_mode:true,
      delivery_title:"Pedir a domicilio",delivery_desc:"Recibe tu pedido en casa",delivery_icon:"🛵",
      pickup_title:"Recoger en el local",pickup_desc:"Pides y recoges tú mismo",
      table_title:"En mesa",table_desc:"Pedido directo a tu mesa",
      notes_placeholder:"Sin cebolla, extra salsa…",
      status_processing_icon:"👨‍🍳",status_processing:"En preparación",status_processing_desc:"¡Tu pedido está siendo preparado!",
      status_ready:"Listo para entregar",status_ready_desc:"Tu pedido está listo. ¡Pronto saldrá!",
      status_shipping_icon:"🛵",status_shipping:"¡En camino!",status_shipping_desc:"Tu domicilio está en camino.",
      status_done:"¡Entregado!",status_done_desc:"¡Buen provecho!",
      delivery_fee_label:"Domicilio",confirm_btn:"Confirmar pedido",
      cart_title:"Tu pedido",checkout_title:"Tus datos",summary_title:"Pago y resumen"},
    emojis:["🔥","🍕","🌮","🍣","🥩","🍔","🍗","🥗","☕","🍺","🧇","🐟"],
  },
  fashion:{
    id:"fashion",name:"Moda & Ropa",icon:"👗",color:"#ec4899",
    desc:"Tiendas de ropa, calzado, accesorios, boutiques",
    labels:{catalog:"Catálogo",item:"Prenda",itemPlural:"Prendas",category:"Colección",categoryPlural:"Colecciones",
      order:"Pedido",delivery:"Envío",branch:"Tienda",stock:"Inventario",
      design:"Diseño de la tienda",nav_products:"👗 Catálogo",nav_delivery:"📦 Envíos / Pedidos",
      nav_design:"🎨 Diseño de la tienda",nav_stock:"🚫 Sin stock",
      nav_branches:"🏪 Tiendas",home_products:"Prendas activas",home_orders:"Pedidos hoy",
      public_title:"Tienda Online",btn_view:"Ver catálogo",cta:"¡Compra ahora!",
      cat_example:"Vestidos de noche",item_example:"Vestido floral manga corta",item_photo:"Foto de la prenda",
      banner_tip:"con la prenda o modelo protagonista centrado y texto corto",
      featured_label:"Destacados",popular_label:"Más vendidos",catalog_btn:"🛍️ Ver catálogo completo",
      how_order:"¿Cómo quieres recibirlo?",table_mode:false,
      delivery_title:"Envío a domicilio",delivery_desc:"Recibe tu compra en casa",delivery_icon:"🚚",
      pickup_title:"Recoger en tienda",pickup_desc:"Pides online y recoges tú",
      notes_placeholder:"Talla, color, instrucciones especiales…",
      status_processing_icon:"📦",status_processing:"Procesando pedido",status_processing_desc:"Estamos preparando tu pedido.",
      status_ready:"Listo para envío",status_ready_desc:"Tu pedido está empacado. ¡En camino!",
      status_shipping_icon:"🚚",status_shipping:"¡Enviado!",status_shipping_desc:"Tu pedido está en camino.",
      status_done:"¡Recibido!",status_done_desc:"¡Gracias por tu compra!",
      delivery_fee_label:"Envío",confirm_btn:"Confirmar compra",
      cart_title:"Tu carrito",checkout_title:"Tus datos",summary_title:"Resumen de compra"},
    emojis:["👗","👠","👜","🧢","💍","🕶️","👒","👔","🛍️","✨","💎","🧣"],
  },
  hardware:{
    id:"hardware",name:"Ferretería / Construcción",icon:"🔧",color:"#d97706",
    desc:"Ferreterías, materiales de construcción, herramientas, plomería",
    labels:{catalog:"Catálogo",item:"Producto",itemPlural:"Productos",category:"Categoría",categoryPlural:"Categorías",
      order:"Pedido",delivery:"Entrega",branch:"Local",stock:"Inventario",
      design:"Diseño del catálogo",nav_products:"🔧 Productos",nav_delivery:"🚚 Entregas / Pedidos",
      nav_design:"🎨 Diseño del catálogo",nav_stock:"📦 Sin stock",
      nav_branches:"🏭 Locales",home_products:"Productos activos",home_orders:"Pedidos hoy",
      public_title:"Catálogo Digital",btn_view:"Ver catálogo",cta:"¡Cotiza ahora!",
      cat_example:"Herramientas eléctricas",item_example:"Taladro percutor 1/2\"",item_photo:"Foto del producto",
      banner_tip:"con el producto o marca destacado y texto corto en la imagen",
      featured_label:"Destacados",popular_label:"Más solicitados",catalog_btn:"🔧 Ver catálogo completo",
      how_order:"¿Cómo quieres recibirlo?",table_mode:false,
      delivery_title:"Entrega a domicilio",delivery_desc:"Te lo llevamos donde estás",delivery_icon:"🚚",
      pickup_title:"Recoger en local",pickup_desc:"Pasa por el local a recoger",
      notes_placeholder:"Especificaciones, cantidad, referencia…",
      status_processing_icon:"📦",status_processing:"Procesando pedido",status_processing_desc:"Estamos alistando tu pedido.",
      status_ready:"Listo para entregar",status_ready_desc:"Tu pedido está listo.",
      status_shipping_icon:"🚚",status_shipping:"En camino",status_shipping_desc:"Tu pedido está en camino.",
      status_done:"¡Entregado!",status_done_desc:"¡Gracias por tu pedido!",
      delivery_fee_label:"Entrega",confirm_btn:"Confirmar pedido",
      cart_title:"Tu pedido",checkout_title:"Tus datos",summary_title:"Resumen del pedido"},
    emojis:["🔧","🔨","⚙️","🪛","🪚","🔩","🏗️","🧰","🔌","💡","🪝","🔑"],
  },
  toys:{
    id:"toys",name:"Juguetería / Infantil",icon:"🧸",color:"#8b5cf6",
    desc:"Juguetes, ropa infantil, artículos para bebé, didácticos",
    labels:{catalog:"Catálogo",item:"Juguete",itemPlural:"Juguetes",category:"Categoría",categoryPlural:"Categorías",
      order:"Pedido",delivery:"Envío",branch:"Tienda",stock:"Disponibilidad",
      design:"Diseño de la tienda",nav_products:"🧸 Productos",nav_delivery:"📦 Envíos / Pedidos",
      nav_design:"🎨 Diseño de la tienda",nav_stock:"🚫 Sin stock",
      nav_branches:"🏪 Tiendas",home_products:"Productos activos",home_orders:"Pedidos hoy",
      public_title:"Tienda Infantil",btn_view:"Ver catálogo",cta:"¡Sorprende a los peques!",
      cat_example:"Juguetes educativos",item_example:"Rompecabezas 500 piezas",item_photo:"Foto del juguete",
      banner_tip:"con el juguete o personaje protagonista centrado y texto corto",
      featured_label:"Destacados",popular_label:"Más vendidos",catalog_btn:"🧸 Ver catálogo completo",
      how_order:"¿Cómo quieres recibirlo?",table_mode:false,
      delivery_title:"Envío a domicilio",delivery_desc:"Recibe el regalo en casa",delivery_icon:"🚚",
      pickup_title:"Recoger en tienda",pickup_desc:"Pides y recoges tú mismo",
      notes_placeholder:"Mensaje para regalo, instrucciones especiales…",
      status_processing_icon:"📦",status_processing:"Preparando pedido",status_processing_desc:"Estamos empacando tu pedido.",
      status_ready:"Listo para envío",status_ready_desc:"Tu pedido está listo.",
      status_shipping_icon:"🚚",status_shipping:"¡Enviado!",status_shipping_desc:"Tu pedido está en camino.",
      status_done:"¡Recibido!",status_done_desc:"¡Esperamos que les encante!",
      delivery_fee_label:"Envío",confirm_btn:"Confirmar compra",
      cart_title:"Tu carrito",checkout_title:"Datos de entrega",summary_title:"Resumen de compra"},
    emojis:["🧸","🎮","🎯","🎪","🎨","🎭","🪁","🛝","🎠","🧩","🪀","🎲"],
  },
  beauty:{
    id:"beauty",name:"Belleza & Salud",icon:"💄",color:"#db2777",
    desc:"Salones, spas, cosméticos, farmacias, bienestar",
    labels:{catalog:"Servicios & Productos",item:"Servicio",itemPlural:"Servicios",category:"Categoría",categoryPlural:"Categorías",
      order:"Reserva",delivery:"Domicilio",branch:"Local",stock:"Disponibilidad",
      design:"Diseño del perfil",nav_products:"💄 Servicios",nav_delivery:"📋 Reservas / Pedidos",
      nav_design:"🎨 Diseño del perfil",nav_stock:"🚫 Sin disponibilidad",
      nav_branches:"🏪 Locales",home_products:"Servicios activos",home_orders:"Reservas hoy",
      public_title:"Catálogo & Servicios",btn_view:"Ver servicios",cta:"¡Reserva tu cita!",
      cat_example:"Tratamientos faciales",item_example:"Limpieza profunda de cutis",item_photo:"Foto del servicio",
      banner_tip:"con el servicio o resultado protagonista centrado y texto corto",
      featured_label:"Más populares",popular_label:"Más solicitados",catalog_btn:"💄 Ver todos los servicios",
      how_order:"¿Cómo lo prefieres?",table_mode:false,
      delivery_title:"Servicio a domicilio",delivery_desc:"El servicio llega donde estés",delivery_icon:"🚗",
      pickup_title:"En el local",pickup_desc:"Reserva y visítanos",
      notes_placeholder:"Alergias, preferencias, hora deseada…",
      status_processing_icon:"💆",status_processing:"Confirmando reserva",status_processing_desc:"Estamos confirmando tu reserva.",
      status_ready:"Confirmado",status_ready_desc:"Tu cita está confirmada.",
      status_shipping_icon:"🚗",status_shipping:"En camino",status_shipping_desc:"El profesional está en camino.",
      status_done:"¡Completado!",status_done_desc:"¡Gracias por tu visita!",
      delivery_fee_label:"Desplazamiento",confirm_btn:"Confirmar reserva",
      cart_title:"Tu selección",checkout_title:"Tus datos",summary_title:"Resumen de reserva"},
    emojis:["💄","💅","✂️","🧖","🌸","💆","🧴","💊","🌿","🫧","🪷","💋"],
  },
  tech:{
    id:"tech",name:"Tecnología / Electrónica",icon:"📱",color:"#2563eb",
    desc:"Celulares, computadores, accesorios tech, reparaciones",
    labels:{catalog:"Catálogo Tech",item:"Equipo",itemPlural:"Equipos",category:"Categoría",categoryPlural:"Categorías",
      order:"Pedido",delivery:"Envío",branch:"Tienda",stock:"Inventario",
      design:"Diseño de la tienda",nav_products:"📱 Productos",nav_delivery:"📦 Envíos / Pedidos",
      nav_design:"🎨 Diseño de la tienda",nav_stock:"🚫 Sin stock",
      nav_branches:"🏪 Tiendas",home_products:"Equipos activos",home_orders:"Pedidos hoy",
      public_title:"Tienda Tech",btn_view:"Ver catálogo",cta:"¡Compra tech!",
      cat_example:"Celulares y tablets",item_example:"iPhone 15 Pro 256GB",item_photo:"Foto del equipo",
      banner_tip:"con el equipo o marca protagonista centrado y texto corto",
      featured_label:"Lo nuevo",popular_label:"Más vendidos",catalog_btn:"📱 Ver catálogo tech",
      how_order:"¿Cómo quieres recibirlo?",table_mode:false,
      delivery_title:"Envío a domicilio",delivery_desc:"Recibe tu equipo en casa",delivery_icon:"🚚",
      pickup_title:"Recoger en tienda",pickup_desc:"Pasa por la tienda a reclamar",
      notes_placeholder:"Modelo, color, especificaciones…",
      status_processing_icon:"📦",status_processing:"Procesando pedido",status_processing_desc:"Verificando disponibilidad de tu equipo.",
      status_ready:"Listo para envío",status_ready_desc:"Tu equipo está empacado.",
      status_shipping_icon:"🚚",status_shipping:"¡Enviado!",status_shipping_desc:"Tu pedido está en camino.",
      status_done:"¡Recibido!",status_done_desc:"¡Disfruta tu nuevo equipo!",
      delivery_fee_label:"Envío",confirm_btn:"Confirmar compra",
      cart_title:"Tu carrito",checkout_title:"Datos de envío",summary_title:"Resumen de compra"},
    emojis:["📱","💻","🖥️","⌨️","🖱️","🎧","📷","🔋","💾","🖨️","📡","🎮"],
  },
  grocery:{
    id:"grocery",name:"Tienda / Supermercado",icon:"🛒",color:"#059669",
    desc:"Tiendas de barrio, supermercados, abarrotes, minimarkets",
    labels:{catalog:"Catálogo",item:"Producto",itemPlural:"Productos",category:"Sección",categoryPlural:"Secciones",
      order:"Pedido",delivery:"Domicilio",branch:"Punto de venta",stock:"Inventario",
      design:"Diseño de la tienda",nav_products:"🛒 Productos",nav_delivery:"🛵 Domicilios / Pedidos",
      nav_design:"🎨 Diseño de la tienda",nav_stock:"📦 Sin stock",
      nav_branches:"🏪 Puntos de venta",home_products:"Productos activos",home_orders:"Pedidos hoy",
      public_title:"Tienda Online",btn_view:"Ver productos",cta:"¡Pide a domicilio!",
      cat_example:"Frutas y verduras",item_example:"Aguacate Hass x unidad",item_photo:"Foto del producto",
      banner_tip:"con el producto o categoría protagonista centrado y texto corto",
      featured_label:"Destacados",popular_label:"Más pedidos",catalog_btn:"🛒 Ver todos los productos",
      how_order:"¿Cómo quieres recibirlo?",table_mode:false,
      delivery_title:"Domicilio",delivery_desc:"Recibe tu mercado en casa",delivery_icon:"🛵",
      pickup_title:"Recoger en tienda",pickup_desc:"Pasa y recoge tu pedido",
      notes_placeholder:"Sustituciones, cantidades exactas, instrucciones…",
      status_processing_icon:"🛒",status_processing:"Alistando pedido",status_processing_desc:"Estamos seleccionando tus productos.",
      status_ready:"Listo para despacho",status_ready_desc:"Tu pedido está listo.",
      status_shipping_icon:"🛵",status_shipping:"¡En camino!",status_shipping_desc:"Tu pedido viene en camino.",
      status_done:"¡Entregado!",status_done_desc:"¡Buen provecho!",
      delivery_fee_label:"Domicilio",confirm_btn:"Confirmar pedido",
      cart_title:"Tu pedido",checkout_title:"Tus datos",summary_title:"Pago y resumen"},
    emojis:["🛒","🏪","🥦","🧀","🥩","🍎","🧃","🥫","🧹","🏷️","🛍️","🌽"],
  },
  pets:{
    id:"pets",name:"Mascotas & Veterinaria",icon:"🐾",color:"#d97706",
    desc:"Petshops, veterinarias, grooming, accesorios para mascotas",
    labels:{catalog:"Catálogo",item:"Producto",itemPlural:"Productos",category:"Categoría",categoryPlural:"Categorías",
      order:"Pedido",delivery:"Envío",branch:"Tienda",stock:"Disponibilidad",
      design:"Diseño de la tienda",nav_products:"🐾 Productos",nav_delivery:"📦 Envíos / Pedidos",
      nav_design:"🎨 Diseño de la tienda",nav_stock:"🚫 Sin stock",
      nav_branches:"🏪 Tiendas",home_products:"Productos activos",home_orders:"Pedidos hoy",
      public_title:"Tienda de Mascotas",btn_view:"Ver catálogo",cta:"¡Todo para tu mascota!",
      cat_example:"Alimentos para perros",item_example:"Concentrado Royal Canin 15kg",item_photo:"Foto del producto",
      banner_tip:"con la mascota o producto protagonista centrado y texto corto",
      featured_label:"Destacados",popular_label:"Más vendidos",catalog_btn:"🐾 Ver catálogo completo",
      how_order:"¿Cómo quieres recibirlo?",table_mode:false,
      delivery_title:"Envío a domicilio",delivery_desc:"Lo recibe tu mascota en casa",delivery_icon:"🚚",
      pickup_title:"Recoger en tienda",pickup_desc:"Pasa por la tienda",
      notes_placeholder:"Raza, peso, edad de tu mascota, instrucciones…",
      status_processing_icon:"📦",status_processing:"Preparando pedido",status_processing_desc:"Estamos alistando tu pedido.",
      status_ready:"Listo para envío",status_ready_desc:"Tu pedido está listo.",
      status_shipping_icon:"🚚",status_shipping:"¡Enviado!",status_shipping_desc:"Tu pedido está en camino.",
      status_done:"¡Recibido!",status_done_desc:"¡Que lo disfrute tu mascota!",
      delivery_fee_label:"Envío",confirm_btn:"Confirmar pedido",
      cart_title:"Tu pedido",checkout_title:"Tus datos",summary_title:"Resumen del pedido"},
    emojis:["🐾","🐕","🐈","🦜","🐠","🐹","🦴","🐾","🧴","🏥","💊","🛁"],
  },
  services:{
    id:"services",name:"Servicios Profesionales",icon:"🏢",color:"#4338ca",
    desc:"Talleres, consultorías, agencias, servicios técnicos",
    labels:{catalog:"Portafolio",item:"Servicio",itemPlural:"Servicios",category:"Categoría",categoryPlural:"Categorías",
      order:"Cotización",delivery:"Despacho",branch:"Sede",stock:"Disponibilidad",
      design:"Diseño del perfil",nav_products:"🏢 Servicios",nav_delivery:"📋 Cotizaciones",
      nav_design:"🎨 Diseño del perfil",nav_stock:"🚫 No disponible",
      nav_branches:"🏢 Sedes",home_products:"Servicios activos",home_orders:"Cotizaciones hoy",
      public_title:"Portafolio Digital",btn_view:"Ver servicios",cta:"¡Solicita cotización!",
      cat_example:"Reparaciones eléctricas",item_example:"Instalación de tomacorrientes",item_photo:"Foto del servicio",
      banner_tip:"con el servicio o resultado protagonista centrado y texto corto",
      featured_label:"Servicios populares",popular_label:"Más solicitados",catalog_btn:"🏢 Ver portafolio completo",
      how_order:"¿Cómo prefieres el servicio?",table_mode:false,
      delivery_title:"Servicio a domicilio",delivery_desc:"Vamos donde nos necesitas",delivery_icon:"🚗",
      pickup_title:"En nuestra sede",pickup_desc:"Visítanos en la sede",
      notes_placeholder:"Describe lo que necesitas, dimensiones, urgencia…",
      status_processing_icon:"📋",status_processing:"Revisando solicitud",status_processing_desc:"Estamos revisando tu cotización.",
      status_ready:"Cotización lista",status_ready_desc:"Tu cotización está lista para revisar.",
      status_shipping_icon:"🚗",status_shipping:"En camino",status_shipping_desc:"Nuestro equipo está en camino.",
      status_done:"¡Completado!",status_done_desc:"¡Gracias por confiar en nosotros!",
      delivery_fee_label:"Desplazamiento",confirm_btn:"Enviar solicitud",
      cart_title:"Tu selección",checkout_title:"Tus datos",summary_title:"Resumen de solicitud"},
    emojis:["🏢","⚙️","🔨","🚗","🏠","💼","📋","🖥️","🔌","🏗️","🧰","📐"],
  },
};

export const getVertical = t => VERTICALS[t] || VERTICALS.restaurant;

/* ─── HELPERS ─────────────────────────────────────────────── */
